create database sp_exp

CREATE TABLE sp_STUDENT(ID INT IDENTITY(1000,1) PRIMARY KEY,
NAME VARCHAR(200),CELL VARCHAR(200),EMAIL VARCHAR(200));

CREATE PROCEDURE SP_STUDENT_INSERT(@NAME VARCHAR(200),@CELL VARCHAR(200), @EMAIL VARCHAR(200))AS
BEGIN
INSERT INTO sp_STUDENT(NAME,CELL,EMAIL)VALUES(@NAME,@CELL,@EMAIL)
END
USE SP_EXP
select * from sp_STUDENT